# This is a basic workflow to help you get started with Actions

name: AzureWebApps

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    # Build package using Maven
    - name: maven build, clean
      run: |
        mvn clean package -D skipTests
    
    # Maven plugin can cosume this authentication method automatically
    # - name: Azure Login
    #  uses: azure/login@v1
    #  with:
    #    creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Select your way to deploy below
    # (Maven / webapp-deploy with ServicePrincipal / webapp-deploy with PublishProfile)
    
    # Maven deploy, make sure you have correct configurations in your pom.xml
    #- name: deploy to Azure App Service using Maven
    #  run: |
    #    mvn azure-webapp:deploy
    
    # Deploy to Azure WebApp using webapp-deploy
    #- name: 'Deploy to Azure WebApp'
    #  uses: azure/webapps-deploy@v2
    #  with: 
    #    app-name: 'booklist-mynaviazurejava'
    #    package: '${{ github.workspace }}/target/*.jar'
    #      # Deploy to Azure WebApp using webapp-deploy

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'booklist-mynaviazurejava'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ github.workspace }}/target/*.jar'

